<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>

var userRoleRes = {
        title: '<fmt:message key="userRoleRes.title" />',
        lockUser: '<fmt:message key="userRoleRes.lockUser" />',
        disableUser: '<fmt:message key="userRoleRes.disableUser" />',
        unDisableUser: '<fmt:message key="userRoleRes.unDisableUser" />',
        unLockUser: '<fmt:message key="userRoleRes.unLockUser" />',
        editUser: '<fmt:message key="userRoleRes.editUser" />',
        passwordAffirm: '<fmt:message key="userRoleRes.passwordAffirm" />',
        userInfo: '<fmt:message key="userRoleRes.userInfo" />',
        addUser: '<fmt:message key="userRoleRes.addUser" />',
        editRole: '<fmt:message key="userRoleRes.editRole" />',
        addRole: '<fmt:message key="userRoleRes.addRole" />',
        removeRole: '<fmt:message key="userRoleRes.removeRole" />',
        availableFeatures: '<fmt:message key="userRoleRes.availableFeatures" />',
        assignedFeatures: '<fmt:message key="userRoleRes.assignedFeatures" />',
        selectFeature: '<fmt:message key="userRoleRes.selectFeature" />',
        editUserProfile: '<fmt:message key="userRoleRes.editUserProfile" />',
        usernameRegexText: '<fmt:message key="userRoleRes.usernameRegexText" />',
        mobileRegexText: '<fmt:message key="userRoleRes.mobileRegexText" />',
        userCriteria: '<fmt:message key="userRoleRes.userCriteria" />',
        systemCriteria: '<fmt:message key="userRoleRes.systemCriteria" />',
        formsCriteria: '<fmt:message key="userRoleRes.formsCriteria" />',
        flowsCriteria: '<fmt:message key="userRoleRes.flowsCriteria" />',
        msg: {
            editUser: '<fmt:message key="userRoleRes.msg.editUser" />',
            passwordEdit: '<fmt:message key="userRoleRes.msg.passwordEdit" />',
            removeRole: '<fmt:message key="userRoleRes.msg.removeRole" />',
            passwordNotSame: '<fmt:message key="userRoleRes.msg.passwordNotSame" />',
            changePassword: '<fmt:message key="userRoleRes.msg.changePassword" />',
            lockUserSuccess: '<fmt:message key="userRoleRes.msg.lockUserSuccess" />',
            unLockUserSuccess: '<fmt:message key="userRoleRes.msg.unLockUserSuccess" />',
            disableUserSuccess: '<fmt:message key="userRoleRes.msg.disableUserSuccess" />',
            unDisableUserSuccess: '<fmt:message key="userRoleRes.msg.unDisableUserSuccess" />',
            addRoleEmpty: '<fmt:message key="userRoleRes.msg.addRoleEmpty" />',
            addUserHasRole: '<fmt:message key="userRoleRes.msg.addUserHasRole" />',
            removeRoleMsg: '<fmt:message key="userRoleRes.msg.removeRoleMsg" />',
            removeRoleFlowMsg: '<fmt:message key="userRoleRes.msg.removeRoleFlowMsg" />',
            editRole: '<fmt:message key="userRoleRes.msg.editRole" />'
        },
        header: {
            fullName: '<fmt:message key="userRoleRes.header.fullName" />',
            username: '<fmt:message key="userRoleRes.header.username" />',
            defaultRoleName: '<fmt:message key="userRoleRes.header.defaultRoleName" />',
            accountLocked: '<fmt:message key="userRoleRes.header.accountLocked" />',
            password: '<fmt:message key="userRoleRes.header.password" />',
            roleName: '<fmt:message key="userRoleRes.header.roleName" />',
            description: '<fmt:message key="userRoleRes.header.description" />',
            displayName: '<fmt:message key="userRoleRes.header.displayName" />',
            firstName: '<fmt:message key="userRoleRes.header.firstName" />',
            lastName: '<fmt:message key="userRoleRes.header.lastName" />',
            email: '<fmt:message key="userRoleRes.header.email" />',
            mobile: '<fmt:message key="userRoleRes.header.mobile" />',
            managerRole: '<fmt:message key="userRoleRes.header.managerRole" />',
            gender: '<fmt:message key="userRoleRes.header.gender" />',
            defaultContext: '<fmt:message key="userRoleRes.header.defaultContext" />',
            managerContext: '<fmt:message key="userRoleRes.header.managerContext" />',
            userContext: '<fmt:message key="userRoleRes.header.userContext" />',
            roleInfo: '<fmt:message key="userRoleRes.header.roleInfo" />',
            featureName: '<fmt:message key="userRoleRes.header.featureName" />',
            featureCriteria: '<fmt:message key="userRoleRes.header.featureCriteria" />',
            enabled: '<fmt:message key="userRoleRes.header.enabled" />'
        },
        manageUser: '<fmt:message key="userRoleRes.manageUser" />',
        manageRole: '<fmt:message key="userRoleRes.manageRole" />',
        roleName: '<fmt:message key="userRoleRes.roleName" />',
        passwordTilte: '<fmt:message key="userRoleRes.passwordTilte" />',
        oldPassword: '<fmt:message key="userRoleRes.oldPassword" />',
        newPassword: '<fmt:message key="userRoleRes.newPassword" />',
        passwordHint: '<fmt:message key="userRoleRes.passwordHint" />',
        passwordError: '<fmt:message key="userRoleRes.passwordError" />',
        userRoles: '<fmt:message key="userRoleRes.userRoles" />',
        roleFeatures: '<fmt:message key="userRoleRes.roleFeatures" />',
        passwordHitNotAllow: '<fmt:message key="userRoleRes.passwordHitNotAllow" />',
        availableRoles:'<fmt:message key="userRoleRes.availableRoles" />',
        assignedRoles:'<fmt:message key="userRoleRes.assignedRoles" />',
        selectRole: '<fmt:message key="userRoleRes.selectRole" />',
        changeUsers: '<fmt:message key="userRoleRes.changeUsers" />',
        changeRoles: '<fmt:message key="userRoleRes.changeRoles" />',
        departRoles: '<fmt:message key="userRoleRes.departRoles" />',
        changeDepart: '<fmt:message key="userRoleRes.changeDepart" />',
        changeDuty: '<fmt:message key="userRoleRes.changeDuty" />',
        usernameExist: '<fmt:message key="message.error.username.exist" />',
        mobileExist: '<fmt:message key="message.error.getMobileUser.error" />',
        emailExist: '<fmt:message key="message.error.getEmailUser.error" />',
        dummy: ''
};