<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>

var workFlowRes = {
        flowManagerTitle: '<fmt:message key="workFlowRes.flowManagerTitle" />',
        flowDefineManagerTitle: '<fmt:message key="workFlowRes.flowDefineManagerTitle" />',
        flowFormDataManagerTitle: '<fmt:message key="workFlowRes.flowFormDataManagerTitle" />',
        hasDeployment: '<fmt:message key="workFlowRes.hasDeployment" />',
        hasNotDeployment: '<fmt:message key="workFlowRes.hasNotDeployment" />',
        addNewFlow: '<fmt:message key="workFlowRes.addNewFlow" />',
        onlineUpdate: '<fmt:message key="workFlowRes.onlineUpdate" />',
        settingFlow: '<fmt:message key="workFlowRes.settingFlow" />',
        settingFlowRole: '<fmt:message key="workFlowRes.settingFlowRole" />',
        lookHistory: '<fmt:message key="workFlowRes.lookHistory" />',
        flowNotDeployment: '<fmt:message key="workFlowRes.flowNotDeployment" />',
        flowDetails: '<fmt:message key="workFlowRes.flowDetails" />',
        flowHistory: '<fmt:message key="workFlowRes.flowHistory" />',
        flowDeploymentBtn: '<fmt:message key="workFlowRes.flowDeploymentBtn" />',
        flowUserFeature: '<fmt:message key="workFlowRes.flowUserFeature" />',
        changeDeleteFlow: '<fmt:message key="workFlowRes.changeDeleteFlow" />',
        changeDeleteFlowConfirm: '<fmt:message key="workFlowRes.changeDeleteFlowConfirm" />',
        deleteFlow: '<fmt:message key="workFlowRes.deleteFlow" />',
        readdocument: '<fmt:message key="workFlowRes.readdocument" />',
        header: {
            deployment: '<fmt:message key="workFlowRes.header.deployment" />',
            flowName: '<fmt:message key="workFlowRes.header.flowName" />'
        },
        flowIndex: {
            processDefinitionViewDec: '<fmt:message key="workFlowRes.flowIndex.processDefinitionViewDec" />',
            processDefinitionViewTitle: '<fmt:message key="workFlowRes.flowIndex.processDefinitionViewTitle" />',
            taskViewDec: '<fmt:message key="workFlowRes.flowIndex.taskViewDec" />',
            taskViewTitle: '<fmt:message key="workFlowRes.flowIndex.taskViewTitle" />',
            processDefInstanceDraftViewDec: '<fmt:message key="workFlowRes.flowIndex.processDefInstanceDraftViewDec" />',
            processDefInstanceDraftViewTitle: '<fmt:message key="workFlowRes.flowIndex.processDefInstanceDraftViewTitle" />',
            replevyTaskViewDec: '<fmt:message key="workFlowRes.flowIndex.replevyTaskViewDec" />',
            replevyTaskViewTitle: '<fmt:message key="workFlowRes.flowIndex.replevyTaskViewTitle" />',
            applyProcessHistoryViewDec: '<fmt:message key="workFlowRes.flowIndex.applyProcessHistoryViewDec" />',
            applyProcessHistoryViewTitle: '<fmt:message key="workFlowRes.flowIndex.applyProcessHistoryViewTitle" />'
        },
        applyProcessHistoryView: {
            title: '<fmt:message key="workFlowRes.applyProcessHistoryView.title" />',
            searchProcessName: '<fmt:message key="workFlowRes.applyProcessHistoryView.searchProcessName" />',
            searchPstatus: '<fmt:message key="workFlowRes.applyProcessHistoryView.searchPstatus" />',
            searchStartTime: '<fmt:message key="workFlowRes.applyProcessHistoryView.searchStartTime" />',
            searchEndTime: '<fmt:message key="workFlowRes.applyProcessHistoryView.searchEndTime" />',
            runStatus: '<fmt:message key="workFlowRes.applyProcessHistoryView.runStatus" />',
            endStatus: '<fmt:message key="workFlowRes.applyProcessHistoryView.endStatus" />',
            headerTitle: '<fmt:message key="workFlowRes.applyProcessHistoryView.headerTitle" />',
            headerStartTime: '<fmt:message key="workFlowRes.applyProcessHistoryView.headerStartTime" />',
            headerStatus: '<fmt:message key="workFlowRes.applyProcessHistoryView.headerStatus" />',
            headerPrint1: '<fmt:message key="workFlowRes.applyProcessHistoryView.headerPrint1" />',
            headerPrint2: '<fmt:message key="workFlowRes.applyProcessHistoryView.headerPrint2" />'
        },
        countersignTaskWindow: {
            title: '<fmt:message key="workFlowRes.countersignTaskWindow.title" />',
            signType: '<fmt:message key="workFlowRes.countersignTaskWindow.signType" />',
            signTypePerson: '<fmt:message key="workFlowRes.countersignTaskWindow.signTypePerson" />',
            signTypePercent: '<fmt:message key="workFlowRes.countersignTaskWindow.signTypePercent" />',
            signTypeSonTitle: '<fmt:message key="workFlowRes.countersignTaskWindow.signTypeSonTitle" />',
            signTypeCenTitle: '<fmt:message key="workFlowRes.countersignTaskWindow.signTypeCenTitle" />'
        },
        formFieldSetter: {
            title: '<fmt:message key="workFlowRes.formFieldSetter.title" />',
            readable: '<fmt:message key="workFlowRes.formFieldSetter.readable" />',
            writeble: '<fmt:message key="workFlowRes.formFieldSetter.writeble" />',
            hiddenable: '<fmt:message key="workFlowRes.formFieldSetter.hiddenable" />',
            headerVariable: '<fmt:message key="workFlowRes.formFieldSetter.headerVariable" />',
            headerName: '<fmt:message key="workFlowRes.formFieldSetter.headerName" />',
            headerType: '<fmt:message key="workFlowRes.formFieldSetter.headerType" />',
            headerChmod: '<fmt:message key="workFlowRes.formFieldSetter.headerChmod" />',
            headerExpression: '<fmt:message key="workFlowRes.formFieldSetter.headerExpression" />',
            read: '<fmt:message key="workFlowRes.formFieldSetter.read" />',
            write: '<fmt:message key="workFlowRes.formFieldSetter.write" />',
            hidden: '<fmt:message key="workFlowRes.formFieldSetter.hidden" />'
        },
        modeler: {
            startEvent: '<fmt:message key="workFlowRes.modeler.startEvent" />',
            startNone: '<fmt:message key="workFlowRes.modeler.startNone" />',
            taskEvent: '<fmt:message key="workFlowRes.modeler.taskEvent" />',
            userTask: '<fmt:message key="workFlowRes.modeler.userTask" />',
            subProcessTitle: '<fmt:message key="workFlowRes.modeler.subProcessTitle" />',
            subProcess: '<fmt:message key="workFlowRes.modeler.subProcess" />',
            getaway: '<fmt:message key="workFlowRes.modeler.getaway" />',
            exclusive: '<fmt:message key="workFlowRes.modeler.exclusive" />',
            parallel: '<fmt:message key="workFlowRes.modeler.parallel" />',
            inclusive: '<fmt:message key="workFlowRes.modeler.inclusive" />',
            endEvent: '<fmt:message key="workFlowRes.modeler.endEvent" />',
            endNone: '<fmt:message key="workFlowRes.modeler.endNone" />',
            redrawAction: '<fmt:message key="workFlowRes.modeler.redrawAction" />',
            undo: '<fmt:message key="workFlowRes.modeler.undo" />',
            redo: '<fmt:message key="workFlowRes.modeler.redo" />',
            cut: '<fmt:message key="workFlowRes.modeler.cut" />',
            paste: '<fmt:message key="workFlowRes.modeler.paste" />',
            selectVertices: '<fmt:message key="workFlowRes.modeler.selectVertices" />',
            selectEdges: '<fmt:message key="workFlowRes.modeler.selectEdges" />',
            selectAll: '<fmt:message key="workFlowRes.modeler.selectAll" />',
            navGraphTree: '<fmt:message key="workFlowRes.modeler.navGraphTree" />',
            graphProperties: '<fmt:message key="workFlowRes.modeler.graphProperties" />',
            processName: '<fmt:message key="workFlowRes.modeler.processName" />',
            flowFormName: '<fmt:message key="workFlowRes.modeler.flowFormName" />',
            processCategory: '<fmt:message key="workFlowRes.modeler.processCategory" />',
            processDocumentation: '<fmt:message key="workFlowRes.modeler.processDocumentation" />',
            name: '<fmt:message key="workFlowRes.modeler.name" />',
            conditionsequenceflow: '<fmt:message key="workFlowRes.modeler.conditionsequenceflow" />',
            defaultflow: '<fmt:message key="workFlowRes.modeler.defaultflow" />',
            defaultflowNone: '<fmt:message key="workFlowRes.modeler.defaultflowNone" />',
            defaultflowDefault: '<fmt:message key="workFlowRes.modeler.defaultflowDefault" />',
            conditionalflow: '<fmt:message key="workFlowRes.modeler.conditionalflow" />',
            conditionalflowConditional: '<fmt:message key="workFlowRes.modeler.conditionalflowConditional" />',
            formproperties: '<fmt:message key="workFlowRes.modeler.formproperties" />',
            executionlisteners: '<fmt:message key="workFlowRes.modeler.executionlisteners" />',
            looptype: '<fmt:message key="workFlowRes.modeler.looptype" />',
            isforcompensation: '<fmt:message key="workFlowRes.modeler.isforcompensation" />',
            formkeydefinition: '<fmt:message key="workFlowRes.modeler.formkeydefinition" />',
            duedatedefinition: '<fmt:message key="workFlowRes.modeler.duedatedefinition" />',
            prioritydefinition: '<fmt:message key="workFlowRes.modeler.prioritydefinition" />',
            usertaskassignment: '<fmt:message key="workFlowRes.modeler.usertaskassignment" />',
            usertaskassignmentTitle: '<fmt:message key="workFlowRes.modeler.usertaskassignmentTitle" />',
            usertaskassignmentMsg: '<fmt:message key="workFlowRes.modeler.usertaskassignmentMsg" />',
            countersign: '<fmt:message key="workFlowRes.modeler.countersign" />',
            countersignMsg: '<fmt:message key="workFlowRes.modeler.countersignMsg" />',
            asynchronousdefinition: '<fmt:message key="workFlowRes.modeler.asynchronousdefinition" />',
            exclusivedefinition: '<fmt:message key="workFlowRes.modeler.exclusivedefinition" />',
            errorref: '<fmt:message key="workFlowRes.modeler.errorref" />',
            timerdurationdefinition: '<fmt:message key="workFlowRes.modeler.timerdurationdefinition" />',
            timerdatedefinition: '<fmt:message key="workFlowRes.modeler.timerdatedefinition" />',
            timercycledefinition: '<fmt:message key="workFlowRes.modeler.timercycledefinition" />',
            signalref: '<fmt:message key="workFlowRes.modeler.signalref" />',
            zoom: '<fmt:message key="workFlowRes.modeler.zoom" />',
            zoomPercent: '<fmt:message key="workFlowRes.modeler.zoomPercent" />',
            zoomPercentWrite: '<fmt:message key="workFlowRes.modeler.zoomPercentWrite" />',
            zoomIn: '<fmt:message key="workFlowRes.modeler.zoomIn" />',
            zoomOut: '<fmt:message key="workFlowRes.modeler.zoomOut" />',
            zoomActual: '<fmt:message key="workFlowRes.modeler.zoomActual" />',
            preview: '<fmt:message key="workFlowRes.modeler.preview" />',
            nodeAtt: '<fmt:message key="workFlowRes.modeler.nodeAtt" />',
            processPreview: '<fmt:message key="workFlowRes.modeler.processPreview" />',
            startEventMsg: '<fmt:message key="workFlowRes.modeler.startEventMsg" />',
            processDesign: '<fmt:message key="workFlowRes.modeler.processDesign" />'
        },
        newProcessDefinition: {
            save: '<fmt:message key="workFlowRes.newProcessDefinition.save" />',
            start: '<fmt:message key="workFlowRes.newProcessDefinition.start" />',
            mail: '<fmt:message key="workFlowRes.newProcessDefinition.mail" />',
            writeForm: '<fmt:message key="workFlowRes.newProcessDefinition.writeForm" />',
            draftSuc: '<fmt:message key="workFlowRes.newProcessDefinition.draftSuc" />',
            titleNull: '<fmt:message key="workFlowRes.newProcessDefinition.titleNull" />',
            processRunSuc: '<fmt:message key="workFlowRes.newProcessDefinition.processRunSuc" />'
            
        },
        processDefinitionHeader: {
            title: '<fmt:message key="workFlowRes.processDefinitionHeader.title" />',
            remarks: '<fmt:message key="workFlowRes.processDefinitionHeader.remarks" />',
            fileAttachOneName: '<fmt:message key="workFlowRes.processDefinitionHeader.fileAttachOneName" />',
            fileAttachTwoName: '<fmt:message key="workFlowRes.processDefinitionHeader.fileAttachTwoName" />',
            fileAttachThreeName: '<fmt:message key="workFlowRes.processDefinitionHeader.fileAttachThreeName" />',
            uploadFile: '<fmt:message key="workFlowRes.processDefinitionHeader.uploadFile" />',
            download: '<fmt:message key="workFlowRes.processDefinitionHeader.download" />',
            uploadFileTitle: '<fmt:message key="workFlowRes.processDefinitionHeader.uploadFileTitle" />',
            fileName: '<fmt:message key="workFlowRes.processDefinitionHeader.fileName" />',
            buttonText: '<fmt:message key="workFlowRes.processDefinitionHeader.buttonText" />',
            waitMsg: '<fmt:message key="workFlowRes.processDefinitionHeader.waitMsg" />',
            fileLarge: '<fmt:message key="workFlowRes.processDefinitionHeader.fileLarge" />'
        },
        processDefinitionView: {
            title: '<fmt:message key="workFlowRes.processDefinitionView.title" />',
            newProcess: '<fmt:message key="workFlowRes.processDefinitionView.newProcess" />',
            allThe: '<fmt:message key="workFlowRes.processDefinitionView.allThe" />',
            version: '<fmt:message key="workFlowRes.processDefinitionView.version" />',
            suspended: '<fmt:message key="workFlowRes.processDefinitionView.suspended" />',
            notSuspended: '<fmt:message key="workFlowRes.processDefinitionView.notSuspended" />',
            deployDate: '<fmt:message key="workFlowRes.processDefinitionView.deployDate" />',
            readdocumentAlert: '<fmt:message key="workFlowRes.processDefinitionView.readdocumentAlert" />'
        },
        processDefInstanceDraftView: {
            title: '<fmt:message key="workFlowRes.processDefInstanceDraftView.title" />',
            name: '<fmt:message key="workFlowRes.processDefInstanceDraftView.name" />',
            deleteDraft: '<fmt:message key="workFlowRes.processDefInstanceDraftView.deleteDraft" />',
            deleteDraftMsg: '<fmt:message key="workFlowRes.processDefInstanceDraftView.deleteDraftMsg" />'
        },
        processListView: {
            authorization: '<fmt:message key="workFlowRes.processListView.authorization" />',
            authorizationTitle: '<fmt:message key="workFlowRes.processListView.authorizationTitle" />',
            authorizationMsg: '<fmt:message key="workFlowRes.processListView.authorizationMsg" />',
            flowFormName: '<fmt:message key="workFlowRes.processListView.flowFormName" />',
            formTitle: '<fmt:message key="workFlowRes.processListView.formTitle" />',
            design: '<fmt:message key="workFlowRes.processListView.design" />',
            checkProcessRunning: '<fmt:message key="workFlowRes.processListView.checkProcessRunning" />',
            checkProcessRunning1: '<fmt:message key="workFlowRes.processListView.checkProcessRunning1" />',
            depProcess: '<fmt:message key="workFlowRes.processListView.depProcess" />',
            disAuthorization: '<fmt:message key="workFlowRes.processListView.disAuthorization" />',
            disAuthorizationProcessMsg: '<fmt:message key="workFlowRes.processListView.disAuthorizationProcessMsg" />',
            disAuthorizationProcessAlert: '<fmt:message key="workFlowRes.processListView.disAuthorizationProcessAlert" />',
            deleteProcess: '<fmt:message key="workFlowRes.processListView.deleteProcess" />',
            depSuc: '<fmt:message key="workFlowRes.processListView.depSuc" />'
        },
        processUserSetter: {
            assignment_type: '<fmt:message key="workFlowRes.processUserSetter.assignment_type" />',
            assignee: '<fmt:message key="workFlowRes.processUserSetter.assignee" />',
            candidateUsers: '<fmt:message key="workFlowRes.processUserSetter.candidateUsers" />',
            candidateRoles: '<fmt:message key="workFlowRes.processUserSetter.candidateRoles" />',
            assValue: '<fmt:message key="workFlowRes.processUserSetter.assValue" />'
        },



        dummy: ''
};